import { StockTakeCatalogItem } from './stock-take.types';

export const DEFAULT_STOCK_ITEM_CATALOG: StockTakeCatalogItem[] = [
  {
    id: 1,
    name: 'Wings',
    supplier: 'Service Food',
    unit: 'kg',
    area: 'Fridge',
    idealStock: 15,
  },
  {
    id: 2,
    name: 'Dry Tomato',
    supplier: 'Service Food',
    unit: 'kg',
    area: 'Fridge',
    idealStock: 1,
  },
  {
    id: 3,
    name: 'Halloumi',
    supplier: 'Service Food',
    unit: 'kg',
    area: 'Fridge',
    idealStock: 3,
  },
  {
    id: 4,
    name: 'Bacon',
    supplier: 'Service Food',
    unit: 'kg',
    area: 'Fridge',
    idealStock: 4,
  },
  {
    id: 5,
    name: 'Potato',
    supplier: 'Service Food',
    unit: 'kg',
    area: 'Fridge',
    idealStock: 5,
  },
  {
    id: 6,
    name: 'Salsa',
    supplier: 'Produto da casa',
    unit: 'kg',
    area: 'Fridge',
    idealStock: 4,
  },
  {
    id: 7,
    name: 'Tomato',
    supplier: 'Fresh Produce Co',
    unit: 'kg',
    area: 'Fridge',
    idealStock: 5,
  },
  {
    id: 8,
    name: 'Red Onion',
    supplier: 'Fresh Produce Co',
    unit: 'kg',
    area: 'Dry Section',
    idealStock: 10,
    critical: true,
  },
  {
    id: 9,
    name: 'Fries',
    supplier: 'Service Food',
    unit: 'unit',
    area: 'Freezer',
    idealStock: 30,
    critical: true,
  },
  {
    id: 10,
    name: 'Tender',
    supplier: 'Service Food',
    unit: 'kg',
    area: 'Pizza Fridge',
    idealStock: 4,
  },
  {
    id: 11,
    name: 'Chicken Breast',
    supplier: 'Service Food',
    unit: 'kg',
    area: 'Fridge',
    idealStock: 12,
  },
];
